name: CI

on:
  push:
    tags: v*.*.*

permissions:
  contents: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev

      - uses: actions/setup-go@v6
        with:
          go-version-file: src/go.mod
          cache-dependency-path: src/go.sum

      - name: Install
        run: make install

      - name: Test
        run: make test

  build:
    needs: test
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux ]
        arch: [ amd64 ]
    steps:
      - uses: actions/checkout@main

      - run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev

      - uses: actions/setup-go@v6
        with:
          go-version-file: src/go.mod
          cache-dependency-path: src/go.sum

      - run: sudo apt-get install -y upx-ucl

      - name: Install
        run: make install

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: make build

      - name: Package
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: make package

      - run: mv dist/dsync dist/dsync_${{ matrix.os }}_${{ matrix.arch }}

      - uses: actions/upload-artifact@v7
        with:
          name: build_${{ matrix.os }}_${{ matrix.arch }}
          path: dist/

  release:
    needs: build
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: dist
          pattern: build_*_*
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          name: Empty Audio ${{ github.ref_name }}
          files: dist/*